version: '3.8'

services:
  db:
    container_name: mysql_8
    build: .
    image: mysql:8.0
    command: ['--default-authentication-plugin=mysql_native_password']
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '3306:3306'
    networks:
      - wpsite

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      PMA_USER: root  
      PMA_PASSWORD: root
    networks:
      - wpsite

networks:
  wpsite:
    external: true  # Использование внешней сети
