version: '3.8'

services:
  db:
    container_name: mysql_8
    build: .
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '3307:3306'
    volumes: 
      - ./data:/var/lib/mysql  # Монтируем volume для хранения данных
    networks:
      - wpsite
      
  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      PMA_USER: root  
      PMA_PASSWORD: root
    networks:
      - wpsite

networks:
  wpsite:
    external: true  # Использование внешней сети
    
volumes:
  mysql_data:  # Это создаст volume, в котором будут храниться все данные MySQL
