version: '3.1'

services:
  clickhouse-server:
    image: yandex/clickhouse-server:latest
    restart: always
    container_name: clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./data:/var/lib/clickhouse # Монтируем volume для хранения данных
