version: '3.8'

services:
  composer:
    image: composer:1
    networks:
      - wpsite

  php:
    container_name: php_7.4
    build: .
    image: php:7.4-fpm
    ports:
      - "9900:9000"
    volumes:
      - /home/yuriy/projects/tyres:/home/yuriy/projects/tyres
      - /home/yuriy/.ssh:/root/.ssh
    extra_hosts:
      - "git.tyres.spb.ru:10.172.100.148"
      - "host.docker.internal:host-gateway"
    networks:
      - wpsite

networks:
  wpsite:
    external: true  # Использование внешней сети
